name: Refresh SNAP API
on: 
  push:
    branches:
      - main
jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
    - name: Refresh API
      uses: satak/webrequest-action@master
      with:
        url: http://earthmaps.io:6081/update/
        method: GET
